// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { resolve } from 'path';

// Load .env from project root (assuming Prisma commands run from apps/api)
// Go up two levels from apps/api to reach project root
dotenv.config({ path: resolve(process.cwd(), '../../.env') });
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
